Repository UjjwalSaini07/VedicSadhana, pull requests merged in 2024-06, with the labels that each got.

#1 Update README.md
  README.md
Labels: documentation, enhancement

#2 Making AboutUs Page Responsive
  src/components/AboutUs.js
Labels: enhancement

#10 Adding Voice Read Capability to all Sholas Section in Different Languages
  public/index.html
  src/App.css
  src/components/AudioRead.js
  src/components/Homeque.js
Labels: enhancement, Ui Enhancement

#11 Adjusting the positioning of Button on Homepage
  src/pages/Home.js
  src/pages/home.css
Labels: Ui Enhancement

#18 Improved the changes made to resolve issue #7
  src/components/Homeque.js
  src/components/Icon.svg
  src/components/style.css
Labels: enhancement, Ui Enhancement

#20 Resolves #17
  src/components/Chapters.js
Labels: enhancement

#22 Make Changes According to Online Webpage
  src/components/Chapters.js
Labels: Bug Fixing

#23 Fixing Chapter.js Separators
  src/components/Chapters.js
Labels: enhancement, Bug Fixing

#24 Add Arrow for Fast travelling
  src/components/Chapters.js
Labels: Ui Enhancement

#25 Big Changes In Contact Section
  src/pages/Contact.js
Labels: Ui Enhancement, Great Change, Animated, Solve Issue

#28 Fixing The Navbar
  src/components/Navbar.js
Labels: enhancement, Ui Enhancement, Bug Fixing, Great Change, Solve Issue, HardWork

#29 Shifting Towards right Logounder
  src/components/Navbar.js
Labels: duplicate, enhancement

#30 Addon in Resource Page
  src/assets/images/Contact us-amico.png
  src/assets/images/Contact us.gif
  src/assets/images/Generated_Caller.jpg
  src/components/Resource_Image/Brahmanas.jpg
  src/components/Resource_Image/GarudaPuran.jpg
  src/components/Resource_Image/MatsyaPuran.jpg
  src/components/Resource_Image/Puranas.jpg
  src/components/Resource_Image/RigVeda_Brahmanas.jpg
  src/components/Resource_Image/Shiva-Purana-Sanskrit.jpg
  src/components/Resource_Image/ShivaPurana.jpg
  src/components/Resource_Image/The Agni-Purana.jpg
  src/components/Resource_Image/Vedangas.jpg
  src/components/Resources.js
Labels: Great Change

#32 Adding Chronicle Section and Install required Libraries or modules
  package-lock.json
  package.json
  src/App.js
  src/components/Carousel_Images/Mahabharat/Karna.jpg
  src/components/Carousel_Images/Ramyana/JaiShreeRam.jpg
  src/components/Carousel_Images/Ramyana/ShreeRam.jpg
  src/components/Chronicle.jsx
  src/components/Navbar.js
Labels: enhancement

#40 Adding chronicle linkage with files
  package-lock.json
  package.json
  src/App.js
  src/components/Carousel_Images/CoverImages/Mahabharat_Image.jpg
  src/components/Carousel_Images/CoverImages/Ramayana_Image.jpg
  src/components/Chronicle.jsx
  src/components/Mahabharat_carousel.jsx
  src/components/Ramayana_carousel.jsx
Labels: enhancement

#43 Less the volume of audio file
  src/components/Chronicle.jsx
Labels: duplicate

#44 Mahabharat Carousel is Ready
  package-lock.json
  package.json
  src/App.js
  src/assets/images/contact.png
  src/components/Chronicle.jsx
  src/components/Mahabharat_carousel.js
  src/components/Mahabharat_carousel.jsx
Labels: enhancement, Ui Enhancement, Bug Fixing, Great Change, Animated, Solve Issue, HardWork

#46 Adding Voice Read Capability in Chapter Summary Section
  src/components/Chapters.js
Labels: Ui Enhancement, Bug Fixing, Great Change, Solve Issue, HardWork

#47 Adding Ramayana Carousel Section
  src/components/Carousel_Images/Ramyana/_01.jpg
  src/components/Carousel_Images/Ramyana/_Logo.png
  src/components/Ramayana_carousel.js
  src/components/Ramayana_carousel.jsx
Labels: Great Change, Animated

#49 Update Contact.js
  src/pages/Contact.js
Labels: duplicate

#50 Fix All Issues in Contact Page
  package-lock.json
  src/pages/Contact.js
Labels: Ui Enhancement, Great Change, Solve Issue

#53 Adding link in resource page
  package-lock.json
  package.json
  src/components/Resource_Image/Kalki.jpg
  src/components/Resource_Image/Mahabharat.jpg
  src/components/Resource_Image/VishnuPuranas.jpg
  src/components/Resource_Image/upanishads.jpg
  src/components/Resources.js
Labels: Ui Enhancement, Animated, Solve Issue

#54 Make a new About Us Page
  src/components/AboutUs.js
  src/components/krishnabg.png
Labels: enhancement, Ui Enhancement, Great Change, HardWork
